### ISSUE TITLE
Folders are not listed for s3 storage

### ISSUE THREAD

**Issue by alenoosh** [barryvdh/laravel-elfinder#102]
Hi

I'm using the elfinder for listing all my files and folders from a s3 bucket, but it does not list the folders.

Here is my config/elfinder.php :

``````
<?php

return array(

    'dir' => ['files'],

     'disks' => [
            's3'
    ],

    'route' => [
        'prefix' => 'elfinder'
    ],

    'access' => 'Barryvdh\Elfinder\Elfinder::checkAccess',

    'roots' => null,

    'options' => array()
);
`````
and my config/filesystems.php :

`````
return [

    'default' => 's3',

    'cloud' => 's3',

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root'   => storage_path('app'),
        ],

        'ftp' => [
            'driver'   => 'ftp',
            'host'     => 'ftp.example.com',
            'username' => 'your-username',
            'password' => 'your-password',

            // Optional FTP Settings...
            // 'port'     => 21,
            // 'root'     => '',
            // 'passive'  => true,
            // 'ssl'      => true,
            // 'timeout'  => 30,
        ],

        's3' => [
                'driver' => 's3',
                'key'    => 'key',
                'secret' => 'secret',
                'region' => 'region',
                'bucket' => 'bucketname'
        ],

        'rackspace' => [
            'driver'    => 'rackspace',
            'username'  => 'your-username',
            'key'       => 'your-key',
            'container' => 'your-container',
            'endpoint'  => 'https://identity.api.rackspacecloud.com/v2.0/',
            'region'    => 'IAD',
            'url_type'  => 'publicURL',
        ],
    ],
];
``````

I know that elfinder supports listing of directories but it fails to list directories from s3 cloud storage.

Is there any solution for this ?

**Comment by mln-mln-mln** [comment]
I have the same issue. Did you found a solution for this?

**Comment by serverfire** [comment]
@mln-mln-mln No I haven't find any solution. I stopped using elfinder.

**Comment by barryvdh** [comment]
@serverfire What do you use now?

This is probably an issue with https://github.com/barryvdh/elfinder-flysystem-driver
I haven't tested that with S3, but should work like any flysystem.

**Comment by serverfire** [comment]
@barryvdh  if you like i can give you a amazon s3 account to take look  , i have spend few days on it and read the elfinder-flysystem-driver but couldn't fix it , we are using elfinder in other projects and would be great if you can take look , it only show the folders of s3 bucket , flysystem work very well with s3 but your code did not work

**Comment by barryvdh** [comment]
Yeah if you can email a test account or something, I'll take a look if I have the time

**Comment by barryvdh** [comment]
Okay created my own test account. So it seems that the `flysystem->has($dir)` doesn't work for directories.

Added a check to get the contents of the parent directoy, and see if any of the directories match. That should fix it, and still be able to create new directories without errors.

Can you guys verify this commit? https://github.com/barryvdh/elfinder-flysystem-driver/commit/c1c099b249147b64c2a269ed3c571fedaba5dc57
Then I can tag a new commit.

**Comment by mln-mln-mln** [comment]
@barryvdh Thank you so much :)  now the directory listing works. And creating a directory works only for root folder, but doesnt refreshes the page to show the newly created directory. 

And still creating directories inside directory doesnt work. It throws error message and the folder isnt created at all.
