### ISSUE TITLE
PHP7 support? Error: Unable to connect to backend.

### ISSUE THREAD

**Issue by Joakimpsd** [barryvdh/laravel-elfinder#106]
I'm running PHP7 on my production server, and elffinder doesn't work there, but it works in my Homestead box with PHP5 so i guess this is not compatible with PHP7? 

Error:
ErrorException in elFinder.class.php line 237:
session_start(): open(/var/lib/php5/sessions/sess_2iauqermgohqc9h6cbv67h8721, O_RDWR) failed: No such file or directory (2)

**Comment by Joakimpsd** [comment]
It works if i just comment out the session_start() statement, is this something wrong in my conf since session_start looks for php5 session folder?

**Comment by barryvdh** [comment]
Can you ask here? https://github.com/Studio-42/elFinder
THis is just a Laravel wrapper.
