### ISSUE TITLE
Declaration of Barryvdh\elFinderFlysystemDriver\Driver::resize()

### ISSUE THREAD

**Issue by eldor** [barryvdh/laravel-elfinder#119]
Hi, 

I have a problem with the elfinder package.

I get the following error when trying to see whats happening with the connector:

URL: connector?_token=&cmd=open&target=&init=1&tree=1&_=1453378278056

Declaration of Barryvdh\elFinderFlysystemDriver\Driver::resize() should be compatible with elFinderVolumeDriver::resize($hash, $width, $height, $x, $y, $mode = 'resize', $bg = '', $degree = 0, $jpgQuality = NULL)

I'm using version 0.3.5

**Comment by barryvdh** [comment]
are you using the latest build from https://github.com/studio-42/elfinder ?

**Comment by eldor** [comment]
Thats a very good question. 
I suppose its the latest, its downloaded when installing the elfinder package.

 Installing studio-42/elfinder (2.1.6)
    Loading from cache

**Comment by barryvdh** [comment]
Can you try the `0.3.x@dev` version from laravel-elfinder?

**Comment by eldor** [comment]
Removing barryvdh/laravel-elfinder (v0.3.5)
  - Installing barryvdh/laravel-elfinder (dev-master 35f8485)
    Loading from cache

Same issue:

ErrorException in Driver.php line 17:
Declaration of Barryvdh\elFinderFlysystemDriver\Driver::resize() should be compatible with elFinderVolumeDriver::resize($hash, $width, $height, $x, $y, $mode = 'resize', $bg = '', $degree = 0, $jpgQuality = NULL)

**Comment by barryvdh** [comment]
Sorry, can you try:

`composer require barryvdh/elfinder-flysystem-driver:"0.1.x@dev"` also?

**Comment by eldor** [comment]
That did the trick :-)
Just out of curiosity what was the problem?

**Comment by barryvdh** [comment]
I should need to tag a new release for that package after https://github.com/barryvdh/elfinder-flysystem-driver/pull/16  :)

**Comment by eldor** [comment]
Ok, thx for the help and really quick response.
Im closing the issue now :D

**Comment by barryvdh** [comment]
Pushed a new release, so in a couple of minutes it should be good by default :)
