### ISSUE TITLE
problem with middleware

### ISSUE THREAD

**Issue by AmrAlfoly** [barryvdh/laravel-elfinder#127]
when i set the middleware to 'auth' and try to access elinder
it redirects to the /admin route which i configured to be as redirect to after login
i only need to protect the elfinder route with the auth middleware

**Comment by rebootcode** [comment]
I have exactly same problem, did you find the solution ?

When setting middleware to `NULL` , it opens fine, but when setting middleware to 'auth` , It redirects to home page.

**Comment by sisve** [comment]
This occurs in Laravel 5.2 if you're using a session based login (which the default is), and forget to include the "web" middleware group.

`'middleware' => array('web', 'auth')`

**Comment by rebootcode** [comment]
https://github.com/lavaio/elfinder-bug   :+1:

**Comment by ahmadbadpey** [comment]
This occurs in Laravel 5.3 too and with @sisve approach it solved.

**Comment by barryvdh** [comment]
I've updated the config to use web + auth by default.

**Comment by DKWBL** [comment]
@barryvdh i delete auth from the array, but i always redirect to login page.
Clean lara 5.6 project.
If i pass // 
        $router->group(['prefix'=>'elfinder', 'namespace'=>'Barryvdh\Elfinder'], function($router)
it works
but with $config where middleware is set to null - doesn't
