### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by joaonzangoII** [barryvdh/laravel-elfinder#130]
Getting this weird error on my production environment ```elfinder debug: [error] [elfinder] Array to string conversion```

**Comment by AmrAlfoly** [comment]
yes it happened after composer has updated elfinder-flysystem-driver
please how to fix this?

**Comment by joaonzangoII** [comment]
@AmrAlfoly I have been trying to trace the error but until now no luck on my side!

**Comment by joaonzangoII** [comment]
This problem seems to get resolved as soon as you run  ```composer update``` so I am closing this issue.

**Comment by dbr0** [comment]
Today I noticed this for the first time. I haven't been playing around with elfinder for few days while I was doing other things in the code so I could broke something but not sure. `composer update` didn't help me.

**Comment by netmit** [comment]
Same issue here - as soon as I select a file to upload I get the 'array to string conversion' error pop-up.  Again composer update (and removing and requiring again) didn't help. Any ideas?

**Comment by barryvdh** [comment]
@nao-pon, did anything change in the configuration or something tehat you know of?

**Comment by AmrAlfoly** [comment]
@barryvdh nothing changed in the settings and the problem still exists

**Comment by netmit** [comment]
Same here @barryvdh - must have changed during a composer update. Been trying to see where the error is coming from but can't figure it out.

**Comment by netmit** [comment]
Composer update just installed Studio-42/elfinder 2.1.8 and now the array to string conversion error has gone. It's been replaced by an 'Undefined variable: file' error though in the same place (when you browse and select a local file).

**Comment by chrisjohnstone** [comment]
@netmit Yep, I get the same error after running `composer update`.

**Comment by alexusmai** [comment]
installing version 2.1.6 ("studio-42/elfinder": "2.1.6") solved the problem for me

**Comment by barryvdh** [comment]
The last error should be fixed by this: https://github.com/Studio-42/elFinder/pull/1249

**Comment by nao-pon** [comment]
Today, elFinder tagged to 2.1.9. Please try `composer update`.

**Comment by netmit** [comment]
Fixed for me now. Thanks @barryvdh @nao-pon

**Comment by bertalanimre** [comment]
I experience the same issue with 
barryvdh/elfinder-flysystem-driver    v0.1.4  A Flysystem Driver for elFinder
barryvdh/laravel-elfinder             v0.3.5  A Laravel Package to integrate elFinder 2
studio-42/elfinder                    2.1.9   File manager for web

Composer update doesn't help anything. Please tell me what happened and how to resolve this issue?

**Comment by barryvdh** [comment]
Can you expand a bit on the error? Can you post a screenshot? Do you have a stacktrace or something? Can you post your config?

**Comment by bertalanimre** [comment]
1 sec.

**Comment by netmit** [comment]
2.1.9 fixed all the issues for me. 

Just done a new Laravel install and running studio-42/elfinder 2.1.9, barryvdh/elfinder-flysystem-driver 0.1.4 and barryvdh/laravel-elfinder 0.3.5 without problems. (Using CKeditor 4.5.7)

**Comment by bertalanimre** [comment]
Fun fact: 1 developer has no problem locally and he is using 2.1.6. Exact same website on the server with 2.1.9 does not work

**Comment by nao-pon** [comment]
The cause of the "Array to string conversion" error is because the old JavaScript of elFinder.

**Comment by barryvdh** [comment]
So did you guys republish the vendor files?

**Comment by netmit** [comment]
Before 2.1.9 was released I completely removed barryvdh/laravel-elfinder and then added it to composer.json again and did composer update and published the vendor files again - maybe that's why the fix works fine for me?

**Comment by bertalanimre** [comment]
I've solved the issue a very stupid way, but it was an ASAP issue, so whatever works.
I just copied the same folder from another project where it worked and voala. Have no clue why....
P.S.: If I deleted the vendor folder, recreated with composer install, it was still failing.

**Comment by jbajou** [comment]
Installing barryvdh/laravel-elfinder (v0.3.6)
Installing barryvdh/elfinder-flysystem-driver (v0.1.4)
Installing studio-42/elfinder (2.1.9)

Removed vendor folder, 
`composer install`, 
`php artisan vendor:publish --provider='Barryvdh\Elfinder\ElfinderServiceProvider' --tag=config`

Problem NOT solved yet. Any idea ?

**Comment by barryvdh** [comment]
You're updating the config, not the javascript files. Try `php artisan elfinder:publish`

**Comment by jbajou** [comment]
Now that you say it, it's damn obvious! Thanks a lot, that worked.

**Comment by barryvdh** [comment]
This is also recommended in the readme, which suggests to do that after each update:

https://github.com/barryvdh/laravel-elfinder#installation
> You need to copy the assets to the public folder, using the following artisan command:
> `php artisan elfinder:publish`
> Remember to publish the assets after each update (or add the command to your post-update-cmd in composer.json)
