### ISSUE TITLE
Unable to connect to backend. Backend not found. Also - no config files...

### ISSUE THREAD

**Issue by FilipQL** [barryvdh/laravel-elfinder#147]
Hi,

I am using Laravel 5.2 and TinyMCE 4.4.1. I followed the instructions:

1. Installed: barryvdh/laravel-elfinder
2. Added the ServiceProvider to the providers array in app/config/app.php: **Barryvdh\Elfinder\ElfinderServiceProvider::class,**
3. php artisan elfinder:publish
4. Now, when I try to do: `php artisan vendor:publish --provider='Barryvdh\Elfinder\ElfinderServiceProvider' --tag=config` - I get the message: **Nothing to publish for tag [config].**
5. Also, the same goes for: `php artisan vendor:publish --provider='Barryvdh\Elfinder\ElfinderServiceProvider' --tag=views` - **Nothing to publish for tag [views].**

So, in **config** directory there is no **elfinder.php**.

Also, I followed your instructions for TinyMCE integration (4.x) - and it didn't work. I am getting:

> "NetworkError: 404 Not Found - http://localhost/elfinder/tinymce4"

But, when I added 
`
Route::get('/elfinder/tinymce4', [ 'as' => 'elfinder.tinymce4', 'uses' => 'Barryvdh\Elfinder\ElfinderController@showTinyMCE4'] );`

in **routes.php** and when I set **'middleware' => ['web', 'auth'],** in **vendor/barryvdh/laravel-elfinder/config/elfinder.php** - then I get the following error message: **Unable to connect to backend. Backend not found.**  Also, in firebug console there is the following error: **404 Not Found - http://localhost/elfinder/connector?_token=TQTUqxeBKv9uodOyjaWaoE7GOPwS1juvNXpqvf4r&cmd=open&target=&init=1&tree=1&_=1470095805730"**

![project flyer - mozilla firefox 2016-08-02 01 59 35](https://cloud.githubusercontent.com/assets/18264428/17312695/d6eae17c-5854-11e6-81c2-1942bbc83101.png)

**Comment by FilipQL** [comment]
Ok, I added `Barryvdh\Elfinder\ElfinderServiceProvider::class,` below `App\Providers\RouteServiceProvider::class,` and that was the problem. Now, when I put it above - it works.

**Comment by danielcatao** [comment]
`php artisan vendor:publish --provider=**"**Barryvdh\Elfinder\ElfinderServiceProvider**"** --tag=views ` with double quotes works for me

**Comment by danielcatao** [comment]
php artisan vendor:publish --provider="Barryvdh\Elfinder\ElfinderServiceProvider" --tag=views with double quotes works for me

**Comment by danielcatao** [comment]
`php artisan vendor:publish --provider="Barryvdh\Elfinder\ElfinderServiceProvider" --tag=views` with double quotes works for me
