### ISSUE TITLE
named route to showIndex method

### ISSUE THREAD

**Issue by maurocordioli** [barryvdh/laravel-elfinder#155]
in the boot method of the service provider , some routes are conveniently registered with a name

it would be nice  to register also the  route to 'ElfinderController@showIndex' with  name as
` $router->get('/',['as'=>'elfinder.index','uses'=>'ElfinderController@showIndex']);`
instead of using an anonymous route instead of:
`$router->get('/', 'ElfinderController@showIndex');`
 
a component to generate breadcrumbs I'm using does not function when encounters unnamed routes, but  IMHO is of general interest  , to have the @showIndex route named so one can refer  it with the standard route() helper function

**Comment by barryvdh** [comment]
Sure, can you submit a PR ?

**Comment by maurocordioli** [comment]
yes, done, thanks [https://github.com/barryvdh/laravel-elfinder/pull/156](https://github.com/barryvdh/laravel-elfinder/pull/156)
