### ISSUE TITLE
Working localhost but when i uploaded host Invalid backend configuration.

### ISSUE THREAD

**Issue by vsarikaya** [barryvdh/laravel-elfinder#157]
What is wrong? When i upload my files to my host, doesnt work.

> Invalid backend configuration.
Readable volumes not available.

File Structure

> /local
- laravel files (app, bootstrap, config, vendor..)

> /files
- Upload file directory

``` php
'roots' => [
        [
            'driver' => 'LocalFileSystem',
            'path'   => base_path() . '/../files/',
            'URL'    => url('files/')
        ]
    ],
```

and any console errors..

**Comment by barryvdh** [comment]
Is it writable?

**Comment by vsarikaya** [comment]
Yes of course. Permission 777.
