### ISSUE TITLE
I'm using TinyMCE4. What to write to routes.php

### ISSUE THREAD

**Issue by Qh0stM4N** [barryvdh/laravel-elfinder#158]
I'm using TinyMCE4. What to write to routes.php

I'm getting an error :(
elfinder/tinymce4
```
Sorry, the page you are looking for could not be found.

1/1
NotFoundHttpException in RouteCollection.php line 161:
```

**Comment by gzai** [comment]
check your route list in your terminal, and you can see elfinder route
php artisan route:list

**Comment by Qh0stM4N** [comment]
Problem's solved him. But A lot of time after check issue status sorry guys I forgot the solution I followed.
