### ISSUE TITLE
L5.4 works great. Can you please tag it?

### ISSUE THREAD

**Issue by tabacitu** [barryvdh/laravel-elfinder#172]
I've been using the L5.4 updates (the 2 untagged commits) for 7 days and found zero issues, both on L5.3 and L5.4. I think it's stable and ready for a release. The changes are minor and backwards-compatible.

**When do you think you can release the 0.3.10 tag?** 

Thanks a lot, cheers!

**Comment by barryvdh** [comment]
Yes taggec

**Comment by tabacitu** [comment]
Perfect, thank you. Cheers!
