### ISSUE TITLE
 Where and how can i config the tmbURL ? 

### ISSUE THREAD

**Issue by developerpratika** [barryvdh/laravel-elfinder#175]
**Where and how can i config the tmbURL ?** 
in js console it displaying this url
 `
http://genxopto.dev/uploads/.tmb/l1_cHJvZHVjdHNccHJvZHVjdDFcMTIyNzgzYS5qcGc1487745854.png
`
i need
`http://genxopto.dev/public/uploads/.tmb/l1_cHJvZHVjdHNccHJvZHVjdDFcMTIyNzgzYS5qcGc1487745854.png
`
how to change this ?

**Comment by terrylow** [comment]
@developerpratika 

add

`'root_options' => [
        'tmbURL'     => '/uploads/tmb',
        'tmbPath'    => public_path('/uploads/.tmb')
];` to your `/config/elfinder.php`

should get what you demanded

**Comment by developerpratika** [comment]
it is not working 
i tried this before posting this issue

**Comment by developerpratika** [comment]
thank i need to change 
```
 'root_options' => array(         
            'tmbURL' => asset('uploads/.tmb'), 'tmbPath' => public_path('/uploads/.tmb')
    ),
```
Now it is working :)
