### ISSUE TITLE
How to make a folder read-only to certain user type?

### ISSUE THREAD

**Issue by divan-mt** [barryvdh/laravel-elfinder#177]
I would like to give full disk access to the admin and readonly access to the users. How can I achieve this configuration?

**Comment by ercanertan** [comment]
In my case I have done following. But for your case just let admin able to change from backend and done.
in your **AppServiceProvider**


>        try {
>             if (Schema::hasTable('settings')) {
>                 $settings = Setting::pluck('value', 'key')->toArray();
>                 if (isset($settings['media_lock'])) {
>                     if ($settings['media_lock'] == 'false') {
>                         \Config::set(["elfinder.root_options.attributes.0.locked" => false]);
>                     }else{
>                         \Config::set(["elfinder.root_options.attributes.0.locked" => true]);
>                     }
>                 }
>             }
>         } catch (\Illuminate\Database\QueryException $e) {
>             app('log')->error($e->getMessage());
>         }
