### ISSUE TITLE
Flysystem on local disk not create thumbnail images

### ISSUE THREAD

**Issue by hungnm144** [barryvdh/laravel-elfinder#190]
I'm using Flysystem adapters as local disks. this my config:
`    'disks' => [
        'local' => [
            'alias' => 'DISK',
            'path' => 'public/media',
            'URL' => 'storage/media',
            'tmbPath' => storage_path('app/public/media/.tmb')
        ]
    ]
`
All images are saved in the folder "storage/app/public/media" and they can be view from browser normally. But thumbnail images are not working. Directory tmbPath (.tmb) has been created successfully but this folder is empty. How i can fix it :(
![elfinder 2 0](https://user-images.githubusercontent.com/1074467/27994730-4d1c8cce-64ed-11e7-9f3d-8009d8988f8e.png)

**Comment by dcygan** [comment]
Add in config/elfinder.php :

```
'root_options' => array(
        'tmbURL' => '/storage/tmb/',
        'tmbPath' => storage_path('app/public/tmb'),
    ),
```

**Comment by the94air** [comment]
:+1:

**Comment by hungnm144** [comment]
Thanks for support, I've tried but nothing worked :( 
`storage_path('app/public/tmb')` folder was still empty

**Comment by hungnm144** [comment]
Wow, thanks for your support. I've tried and everything working 👍

**Comment by marcelogarbin** [comment]
I have my settings this way:

```
'root_options' => array(
        //'imgLib'      => 'gd',
        'uploadAllow' => array('image/png', 'image/jpeg', 'image/gif'),
        'uploadDeny'  => array('all'),
        'uploadOrder' => array('deny', 'allow'),
        'URL'     => env('APP_URL').'/storage/uploads',
        'tmbUrl'  => env('APP_URL').'/storage/uploads/.tmb',
        'tmbPath' => storage_path('app/public/uploads/.tmb'),
        'attributes' => [
            [
                'pattern' =>  '/\.tmb$/',
                'hidden' => true
            ]
        ]
    ),
```

It does not work at all. Some help? @dcygan

**Comment by hungnm144** [comment]
First, you must create a symbolic link from `storage/app/public/uploads`  to `public`
Run `php artisan storage:link`
And edit your elfinder config at `config/elfinder.php`.
try :
`'disks' => [
        'local' => [
            'alias' => 'LOCAL DISK',
            'path' => 'public/uploads',
            'URL' => '/storage/uploads'
        ]
    ],
'root_options' => array(
        //'imgLib'      => 'gd',
        'uploadAllow' => array('image/png', 'image/jpeg', 'image/gif'),
        'uploadDeny'  => array('all'),
        'uploadOrder' => array('deny', 'allow'),
        'tmbUrl'  => env('APP_URL').'/storage/uploads/.tmb',
        'tmbPath' => storage_path('app/public/uploads/.tmb'),
        'attributes' => [
            [
                'pattern' =>  '/\.tmb$/',
                'hidden' => true
            ]
        ]
    ),
`

**Comment by vahidalvandi** [comment]
> First, you must create a symbolic link from `storage/app/public/uploads` to `public`
> Run `php artisan storage:link`
> And edit your elfinder config at `config/elfinder.php`.
> try :
> 
> ```
> 'disks' => [
>         'local' => [
>             'alias' => 'LOCAL DISK',
>             'path' => 'public/uploads',
>             'URL' => '/storage/uploads'
>         ]
>     ],
> 'root_options' => array(
>         'uploadAllow' => array('image/png', 'image/jpeg', 'image/gif'),
>         'uploadDeny'  => array('all'),
>         'uploadOrder' => array('deny', 'allow'),
>         'tmbUrl'  => env('APP_URL').'/storage/uploads/.tmb',
>         'tmbPath' => storage_path('app/public/uploads/.tmb'),
>         'attributes' => [
>             [
>                 'pattern' =>  '/\.tmb$/',
>                 'hidden' => true
>             ]
>         ]
>     ),
> ```
> 
> @marcelogarbin

not work for me ..

**Comment by mjoris** [comment]
i have been testing your **'root_options'** for some other scenario
it must be
`'tmbURL'  => env('APP_URL') . '/storage/uploads/.tmb',`
in stead of
`'tmbUrl'  => env('APP_URL') . '/storage/uploads/.tmb',`
a nasty typo ... moreover **'tmbPath'** seems not to work without **'tmbURL'**
