### ISSUE TITLE
Deny access to everyone but admins

### ISSUE THREAD

**Issue by robertnicjoo** [barryvdh/laravel-elfinder#195]
Hi,
I just installed this package and it works for me but the link such as `http://xxxx.dev/elfinder/tinymce4` is open to everyone no matter what!

my config is currently like this 

```
'route' => [
        'prefix' => 'elfinder',
        'middleware' => 'isAdmin', //Set to null to disable middleware filter
    ],
```
But seems like middleware doesn't work! how i stop people of having access to that link?

**Comment by MatoH** [comment]
Are you sure that middleware **isAdmin** is working properly? 

I have had an issue that was related to the **middleware problem** - #127 and was solved by adding **web middleware** to elfinder route configuration.
```php
'route' => [
        'prefix' => 'elfinder',
        'middleware' => ['web', 'isAdmin'], //Set to null to disable middleware filter
],
```

**Comment by barryvdh** [comment]
Yeah that should work, but you isAdmin should probably return false when no user is authenticated at all.
