### ISSUE TITLE
can't access URL 'elfinder/ckeditor'

### ISSUE THREAD

**Issue by jmj4you** [barryvdh/laravel-elfinder#207]
Hi,
I just tried this package, i followed everything from readMe after that I call the following URL "http://127.0.0.1/laravel-wrk/public/elfinder/ckeditor"
I got *NotFoundHttpException*

But Route list shows the route
`*GET|HEAD                               | elfinder/ckeditor                              | elfinder.ckeditor   | Barryvdh\Elfinder\ElfinderController@showCKeditor4                  *`

Thanks

**Comment by the94air** [comment]
Can you show me the route code?

**Comment by jmj4you** [comment]
@the94air I haven't added any route for *elfinder* in routes/web.php

I tried in Laravel 5.5 its working fine but my requirement  for Laravel 5.4 and *elfinder* not working for laravel 5.4

**Comment by jmj4you** [comment]
@the94air 
![error-1](https://user-images.githubusercontent.com/1086448/31542420-865284a2-b02f-11e7-84af-e2c3c1c0c5d8.png)

https://github.com/jmj4you/lara-5.4-elFinder

Kindly see the error and my updated code.
Please help me to implement elfinder.

**Comment by the94air** [comment]
Sorry for the late response. here a [PR](https://github.com/jmj4you/lara-5.4-elFinder/pull/1)

**Comment by jmj4you** [comment]
@the94air Thank you very much dude.... 

You saved my one day, your instructions are very helpful and once again thank you for updating code.
Changes merged repository is here https://github.com/jmj4you/lara-5.4-elFinder

Thanks a lot :+1: :100:
