### ISSUE TITLE
Error Unable to connect to backend.

### ISSUE THREAD

**Issue by HenryDewa** [barryvdh/laravel-elfinder#22]
hi i found a problem when trying to upload a file, where the message of the problem is Unable to connect to the backend, and it turns out the problem is because since this function on my filters.php file 

Route :: filter ('CSRF', function () 
{
if (Session :: getToken ()! = Input :: get ('csrf_token') && Session :: getToken ()! = Input :: get ('_token')) 
{
Route::filter('csrf', function()
{
    if (Session::getToken() != Input::get('csrf_token') &&  Session::getToken() != Input::get('_token'))
    {
        throw new Illuminate\Session\TokenMismatchException;
    } 
}); 

How do I deal with these issues?

**Comment by premier213** [comment]
this is not Work for laravel 5.2
