### ISSUE TITLE
How to combine it with Vue-Laravel app?

### ISSUE THREAD

**Issue by DKWBL** [barryvdh/laravel-elfinder#246]
My web.php routes are simple:
Route::get('{any}', function () {
    return view('welcome');
    })->where('any','.*');
    
what should i fix in order to use this package routes in VUE app?

**Comment by DKWBL** [comment]
solved

**Comment by miladganjali** [comment]
Hi @DKWBL how you solve the problem?

**Comment by v-s-public** [comment]
> Hi @DKWBL how you solve the problem?

Hello @miladganjali Do you have answer?

**Comment by miladganjali** [comment]
@v-s-public , No I used another one ckfinder
