### ISSUE TITLE
How to set visibily public when upload to Digital Ocean Spaces

### ISSUE THREAD

**Issue by vanthao03596** [barryvdh/laravel-elfinder#276]
I'm using out package with Digital Ocean Spaces but everthing upload seem private.
How i can setting to upload public like laravel Storage::put('folder', 'file', 'public');

**Comment by promatik** [comment]
@vanthao03596 have you set the File Listing to public?
Digital Ocean > Spaces > File Listing > Enable File Listing

**Comment by vanthao03596** [comment]
> @vanthao03596 have you set the File Listing to public?
> Digital Ocean > Spaces > File Listing > Enable File Listing

I dont use this package anymore. Thanks anyway.
