### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by gorgotluk** [barryvdh/laravel-elfinder#287]
Hi,

Are you planning to adapt elfinder to laravel 8?

**Comment by tabacitu** [comment]
I sure hope so 😄 . Shouldn't be difficult at all, looks like it'll work just fine, please see PR https://github.com/barryvdh/laravel-elfinder/pull/285 . If you could test that and reply to let @barryvdh know that it works for you too, I'm sure it'll give him more confidence to merge the PR - so it could speed up the process.

**Comment by barryvdh** [comment]
Fixed!
