### ISSUE TITLE
Can't resize standalone colorbox 

### ISSUE THREAD

**Issue by mh-jamil** [barryvdh/laravel-elfinder#48]
First of all brilliant work!

Now, I am using elfinder with ckeditor in my website, the only problem I'm facing is resizing the colorbox while opening elfinder standalonepopup. Following is a screenshot of how it looks by default.

http://awesomescreenshot.com/06a4aayl37

I want the colorbox to open and show entire window of elfinder, so height of colorbox needs to be increased. 

I've tried $.colorbox.resize({width:"80%", height:"80%"}); but to no avail. Please suggest how can I do this. 

Regards

**Comment by mh-jamil** [comment]
Hello there, any help?

**Comment by barryvdh** [comment]
You should probably set the options for colorbox:

$(selector).colorbox({width:"80%"});

You need to have Colorbox installed properly. I suggest you ask there.
http://www.jacklmoore.com/colorbox/

**Comment by barryvdh** [comment]
You did try to change it here? https://github.com/barryvdh/laravel-elfinder/blob/master/public/js/standalonepopup.js#L12

**Comment by mh-jamil** [comment]
For the time being, I changed it in vendor/..../views/standalonepopup.php file, it worked. But now after your above comment, I've changed it in public/packages/barryvdh/js/standaloneppopup.js and its working now. 

Thanks

**Comment by barryvdh** [comment]
Okay but you should be careful about both ways, because you override both files when updating/publishing the assets.
Better to export the view and use your own javascript file.

**Comment by mh-jamil** [comment]
How to export the view?

What I've done is, copied the standalonepopup.js file to my own resources and instead of calling it from packages/barryvdh/laravel-elfinder/js/standalonepopup.js I'm now calling it from admin-assets/js/standalonepopup.js

**Comment by barryvdh** [comment]
You can copy the view to app/views/packages/barryvdh/laravel-elfinder/ I think.

**Comment by mh-jamil** [comment]
Will check that. However publishing standalonepopup.js file in my own resources will make sure it won't get overwritten in future. :) 

Thanks for your help with this.
