### ISSUE TITLE
Standalone popup

### ISSUE THREAD

**Issue by matisskeiris** [barryvdh/laravel-elfinder#53]
Hey!
I just added this package, published it and tried to add the standalone popup with the mentioned colorbox
First of all the default JS for this standalone uses the wrong url
`var elfinderUrl = '/elfinder/standalonepopup/';`
Secondly it seems like the route is incorrect because the Controller method showPopup() requires and Laravel throws 
`Missing argument 1 for Barryvdh\Elfinder\ElfinderController::showPopup()`

**Comment by SergeyMiracle** [comment]
Same here...

**Comment by SergeyMiracle** [comment]
To make it work i've changed a few things:
In standalonepopaup.js
```
var elfinderUrl = '/elfinder/popup/';
```
In view - stanalonepopuo.php
```
url: '<?= URL::action('\Barryvdh\Elfinder\ElfinderController@showConnector') ?>',  // connector URL
```

**Comment by barryvdh** [comment]
Was this fixed with this commit? https://github.com/barryvdh/laravel-elfinder/commit/5414db65515c6be9a6dc3f52813876c922850e9b

If so, I can tag a new release

**Comment by SergeyMiracle** [comment]
Looks good, but still need change routes in JS files a guess.

**Comment by barryvdh** [comment]
Can you submit a PR?

**Comment by SergeyMiracle** [comment]
I can i guess, a bit later.

**Comment by SergeyMiracle** [comment]
In master branch it's already fixed

**Comment by barryvdh** [comment]
Okay I tagged v0.3.1
