### ISSUE TITLE
Allow only images to be uploaded

### ISSUE THREAD

**Issue by ayoubbahar** [barryvdh/laravel-elfinder#63]
Hi, what i'm trying to do is to allow only images to be uploaded, but this dosent's seems to work for me, i'm able to upload any kind of files even php files !
i refered to the wiki to see differents options and this is my configuration:

    'roots' => array(
    'accessControl' => 'access'  ,           // disable and hide dot starting files (OPTIONAL)
    'uploadAllow' => array('image'),
    'mimeDetect' => 'internal',
    'imgLib'     => 'gd',
    'uploadOrder'=> array( 'allow', 'deny' )
    ),
any help would be apprecciated, sorry for my bad english

**Comment by ayoubbahar** [comment]
Closed, it's been one year with no comment, I changed the editor and the app is online a long time ago! cheers.

**Comment by rebootcode** [comment]
@ayoubbahar  what app are you using for allowing only image to upload ?
