### ISSUE TITLE
Ability to change thumbnails directory name

### ISSUE THREAD

**Issue by Stichoza** [barryvdh/laravel-elfinder#66]
Need to change thumbnails directory (`files/.tmb` by default) as Apache denies to serve files and folders beginning with a dot.

I checked [elfinder options](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options-2.1) but couldn't find a solution to this issue.

The only solution that came to my mind is to allow `.tmb` in `.htaccess`, but it's a bad idea in general. Is there any way to change thumbnails directory path?

**Comment by Stichoza** [comment]
I was searching in client configuration docs instead of connector. Found it [here](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmbpath). Closing this issue.

BTW #38 might be related to this.

**Comment by barryvdh** [comment]
Perhaps indeed, thanks.

**Comment by Stichoza** [comment]
Seems that `options` has no effect here. Am I doing something wrong?

```
return [
    'dir' => ['files'],
    'disks' => [],
    'route' => [
        'prefix' => 'elfinder',
        'middleware' => 'auth',
    ],
    'access' => 'Barryvdh\Elfinder\Elfinder::checkAccess',
    'roots' => null,
    'options' => [
        'accessControl' => 'access',
        'uploadAllow' => ['image'],
        'mimeDetect' => 'internal',
        'imgLib'     => 'gd',
        'uploadOrder'=> ['allow', 'deny'],
        'tmbPath' => 'thumbs'
    ],
];
```

I can still upload non-image files and thumbnails are still saved to `.tmb`.

(Sorry for long code paste)

**Comment by Claymm** [comment]
Same here with version v0.2.*. Seems like the $options array in config is not affecting anything.

**Comment by Stichoza** [comment]
Okay then I'll reopen this issue. I guess changing thumbnails directory is related to whole `$options` array thing

**Comment by Stichoza** [comment]
Closing. #66 should fix this.
