### ISSUE TITLE
Update to 5.1

### ISSUE THREAD

**Issue by janokary** [barryvdh/laravel-elfinder#78]
Any plans to update to Laravel 5.1?
readme.md needs some update too.

Thanks

**Comment by barryvdh** [comment]
Doesn't it work? What errors do you get?

**Comment by janokary** [comment]
I think I need a more extensive example to get it up and running. 
So it is not about you. It is about me.
I followed the instructions. It went ok after all, but now I am searching about how to use it.
Sorry if the subject of thread was misleading.
Guess I'll have to look for some working examples for 5.1 or 5.x.
Are there any yet?

**Comment by x4n7h1** [comment]
I have this errors:
BadMethodCallException in Filesystem.php line 457:
Call to undefined method League\Flysystem\Filesystem::createDriver
