### ISSUE TITLE
cannot connect to FTP

### ISSUE THREAD

**Issue by kei0719** [barryvdh/laravel-elfinder#81]
hi. I updated laravel-elfinder today to v0.3.4. but couldn't be connect to FTP. The JS error message said status of 500. 

I think what happened problem because of a token. did you change specification to JS?
(I was trying to rollback a version previous one, however restrict 5.0.* of laravel)

here's my environments
Laravel: 5.1.*
FTP environment: proftpd

Thanks.

**Comment by barryvdh** [comment]
What error do you get exactly?

**Comment by kei0719** [comment]
Thanks your reply.

-- error message --

ErrorException in elFinderVolumeFTP.class.php line 340:
Undefined index: owner
-- ---

in case,I did update config file (re-publish vendor.. first requirement) but result was same.
or need to show exact error output?

**Comment by barryvdh** [comment]
You are using the ElfinderFTPFilesystem, or flysystem?

**Comment by kei0719** [comment]
I'm using ElfinderFTPFilesystem puts ftp config info to config/elfinder.php like...

 'roots' => [
        'images' => [
            'alias' => 'aliasName',
            'driver' => 'FTP',
            'host' => '100.0.0',
            'user' => 'user',
            'pass' => 'mypass',
            'port' => 21,
            'mode' => 'active',
            'path' => '/public_html/imageDirExample',
            'URL' => 'imageurl',
            'uploadAllow' => ['image'],
            'tmbPath' => '.tmp',

        ],
    ],

I mean i haven't change any configuration data from previous version.

**Comment by barryvdh** [comment]
can you add `'owner' => true,` ?

**Comment by kei0719** [comment]
I tried it to config/eldinder.php twice just now.

one is inside 'roots' and outside. but it was same result to previous error.

**Comment by kei0719** [comment]
It's solved problem. now working well.
what i've done is, changing FTP config info to config/filesystem.php from config/elfinder.php inside 'roots' array. ( now using Filesystem Disks)

Thanks you.

**Comment by jasneet-bhatia** [comment]
hello,I want to manage files with elfinder.I used ftp in connector file but how i used this without giving ftp details.Is it possible?
