### ISSUE TITLE
"League\Glide\Http\UrlBuilderFactory" not found

### ISSUE THREAD

**Issue by mclxly** [barryvdh/laravel-elfinder#83]
Any help appreciate!

Error: Unable to connect to backend.
Log says "League\Glide\Http\UrlBuilderFactory" not found.

TinyMCE 4.x + Laravel 5.1 + "barryvdh/laravel-elfinder": "^0.3.4"

**Comment by barryvdh** [comment]
If you want to use glide, `composer require league/glide` and set that up.

**Comment by mclxly** [comment]
Thank you very much! It works.
