### ISSUE TITLE
S3 connection

### ISSUE THREAD

**Issue by fernandobandeira** [barryvdh/laravel-elfinder#93]
I'm using Laravel 5.1 with the s3 connector. I have a working filesystem using s3, this is the config:
```
's3' => [
            'driver' => 's3',
            'key'    => '#key',
            'secret' => '#secret',
            'region' => '#region',
            'bucket' => '#bucket',
        ],
```

I'm using it with elfinder, the config for elfinder is as follows:
```
return array(
    'dir' => ['files'],
    'disks' => [
      's3'
    ],
    'route' => [
        'prefix' => 'elfinder',
        'middleware' => 'App\Http\Middleware\AdminMiddleware', //Set to null to disable middleware filter
    ],
    'access' => 'Barryvdh\Elfinder\Elfinder::checkAccess',
    'roots' => null,
    'options' => array(
      'debug' => true,
    ),
);
```
When i open elfinder i get 2 folders on the left panel, the files (on the public directory) and the s3 volume (on amazon). The problem here is that the s3 volume isnt displaying the folders inside the s3 bucket, also i cant create a folder (unable to create folder). The files are showing and i can upload and delete them.

I created a php test page, php can create directories using mkdir on the public folder and can create folders on my s3 bucket using Storage::makeDirectory('a');

Also elfinder creates and shows directories inside the files folder under my public directory.

**Comment by bart** [comment]
How did you solve it? I have the same issue. I see my S3 bucket content but can't move into folders, create new ones etc. The S3 user has a S3 administrative policy.
